In [1]:
import numpy as np

data = np.array([
    [4.5, 2.3, 3.1],
    [5.0, 2.9, 3.5],
    [4.2, 2.5, 3.0],
    [5.1, 3.0, 3.6],
    [4.8, 2.7, 3.2]
])

print(data.shape)  # Output: (5, 3)


(5, 3)


In [4]:
from sklearn.decomposition import PCA
# 建立 PCA 模型並設定要取得的主成分數量
pca = PCA(n_components=2)

# 使用 PCA 來擬合數據並轉換
transformed_data = pca.fit_transform(data)

# 查看前兩個主成分向量
principal_components = pca.components_
print("原始資料:")
print(data)
# 輸出主成分向量和降維後的數據
print("前兩個主成分向量:")
print(principal_components)

print("\n降維後的數據 (2 維):")
print(transformed_data)

原始資料:
[[4.5 2.3 3.1]
 [5.  2.9 3.5]
 [4.2 2.5 3. ]
 [5.1 3.  3.6]
 [4.8 2.7 3.2]]
前兩個主成分向量:
[[ 0.70041464  0.51903736  0.4899179 ]
 [-0.59328941  0.80497598 -0.00462122]]

降維後的數據 (2 維):
[[-0.43951064 -0.17453538]
 [ 0.41808626  0.00995701]
 [-0.59481935  0.16490876]
 [ 0.58902325  0.03066355]
 [ 0.02722049 -0.03099394]]


In [9]:
a=[-0.22, -0.38, -0.18] #去中心化的第一筆資料
b=[ 0.70041464 , 0.51903736 , 0.4899179 ] #第一主成分
dot_product = np.dot(b,a)
print(dot_product) #降維後的數據 (2 維)第一筆資料的第一個特徵

-0.43951063960000003
